name: actions-testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Print current directory
        run: pwd
      - name: Print user information
        run: whoami
      - name: Deliberately fail
        run: exit 1
        