name: actions-testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CONDA_RUN: conda run --name HPC-community-docs-env 
    steps:
      - uses: actions/checkout@v3
      - name: Print current directory and github.workspace
        run: |
          pwd
          echo ${{ github.workspace }}
      - name: Print user information
        run: whoami
      - name: Is Conda installed?
        run: conda info
      # Miniconda is pre-installed in Ubuntu 20.04 runner
      # https://github.com/actions/virtual-environments/blob/ubuntu20/20220330.0/images/linux/Ubuntu2004-Readme.md
      - name: Create Conda environment
        run: conda env create --file environment.yml
      # Use conda run to run commands in an environment. Each job step runs in a
      # separate process, so cannot use conda activate to work in an environment
      - name: Check sphinx-build
        run: ${{ env.CONDA_RUN }} sphinx-build --version
      - name: Build the documentation
        run: ${{ env.CONDA_RUN }} sphinx-build -M html source build
      - name: Upload built HTML documentation artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: built-html-docs
          path: build/html/

