name: actions-testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CONDA_RUN: conda run --name HPC-community-docs-env 
    steps:
      - uses: actions/checkout@v3
      - name: Print current directory and github.workspace
        run: |
          pwd
          echo ${{ github.workspace }}
      - name: Print user information
        run: whoami
      - name: Is Conda installed?
        run: conda info
      # Miniconda is pre-installed in Ubuntu 20.04 runner
      # https://github.com/actions/virtual-environments/blob/ubuntu20/20220330.0/images/linux/Ubuntu2004-Readme.md
      - name: Create Conda environment
        run: conda env create --file environment.yml
      # Use conda run to run commands in an environment. Each job step runs in a
      # separate process, so cannot use conda activate to work in an environment
      - name: Check sphinx-build
        run: ${{ env.CONDA_RUN }} sphinx-build --version
      - name: Build the documentation
        run: ${{ env.CONDA_RUN }} sphinx-build -M html source build
      # Uploaded artifacts are dynamically zipped when accessed through GitHub UI
      # so we do not need to zip them beforehand (this would "double zip" the result)
      # https://github.com/marketplace/actions/upload-a-build-artifact#zipped-artifact-downloads
      - name: Upload built HTML documentation artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: built-html-docs
          path: build/html/
  deploy:
    needs: build
    # TODO Change to restrict to ACRC:main for actions used in production
    # if: >
    #   github.repository == 'ACRC/HPC-community-docs' &&
    #   github.ref == 'refs/heads/main'
    if: >
      github.repository == 'jcwomack/HPC-community-docs' &&
      github.ref == 'refs/heads/prototype/gh-actions'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # actions/checkout required by JamesIves/github-pages-depoy-action
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get github.repository and github.ref values
        run: |
          echo '${{ github.repository}}'
          echo '${{ github.ref }}'
      - name: Download built HTML documentation artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: built-html-docs
          path: _built-html-docs
      - name: Create .nojekyll
        run: touch ${{ steps.download.outputs.download-path }}/.nojekyll
      - name: Display contents of HTML documentation directory
        run: ls -R ${{ steps.download.outputs.download-path }}
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: ${{ steps.download.outputs.download-path }}
          # TODO Limit access of workflow/job through GITHUB_TOKEN to only 
          # necessary permissions
          token: ${{ secrets.GITHUB_TOKEN }}
